"""add_missing_single_column_indices

Revision ID: 0004_single_column_indices
Revises: 0003_phase2_stale_flags
Create Date: 2026-07-14 18:22:59.529788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004_single_column_indices'
down_revision: Union[str, None] = '0003_phase2_stale_flags'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ais_snapshots_bounding_box'), 'ais_snapshots', ['bounding_box'], unique=False)
    op.create_index(op.f('ix_gdelt_articles_corridor'), 'gdelt_articles', ['corridor'], unique=False)
    op.create_index(op.f('ix_risk_scores_corridor'), 'risk_scores', ['corridor'], unique=False)
    op.create_index(op.f('ix_scenario_runs_scenario_id'), 'scenario_runs', ['scenario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_runs_scenario_id'), table_name='scenario_runs')
    op.drop_index(op.f('ix_risk_scores_corridor'), table_name='risk_scores')
    op.drop_index(op.f('ix_gdelt_articles_corridor'), table_name='gdelt_articles')
    op.drop_index(op.f('ix_ais_snapshots_bounding_box'), table_name='ais_snapshots')
    # ### end Alembic commands ###
